# Generated by Django 3.1.3 on 2020-11-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_sub_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
