# Generated by Django 3.1.3 on 2020-11-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201122_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloghead',
            name='is_active',
            field=models.BooleanField(default=True, unique=True),
            preserve_default=False,
        ),
    ]
