# Generated by Django 3.1.3 on 2020-11-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bloghead_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
