# Generated by Django 3.1.3 on 2020-11-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_footercontact_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghead',
            name='is_active',
            field=models.BooleanField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='footercontact',
            name='is_valid',
            field=models.BooleanField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='footercontact',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='is_active',
            field=models.BooleanField(blank=True, unique=True),
        ),
    ]
