# Generated by Django 3.1.3 on 2020-11-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('background_image', models.ImageField(upload_to='background-image')),
                ('head', models.CharField(max_length=150)),
                ('sub_head', models.CharField(max_length=150)),
                ('next_sub_head', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Navigation',
        ),
    ]
